### ISSUE TITLE
First draft dataset docs

### ISSUE THREAD

**Issue by apreshill** [apreshill/bakeoff#1]
Hey @ismayc - ignore vignettes, but please do look at "Reference" here:

https://bakeoff.netlify.com

I cannot for the life of me figure out why this is all scrunched:
<img width="208" alt="screen shot 2018-07-12 at 8 27 56 pm" src="https://user-images.githubusercontent.com/12160301/42670872-3c052418-8612-11e8-8bd2-413a0ebe585c.png">

Ideas?

All the datasets documented so far are "unmerged", so they are barely scraped from Wikipedia and wrangled. I'll make/document merged versions soon. But please feel free to edit current docs if you see places where my documentation could be clarified 😄

**Comment by ismayc** [comment]
Hey @apreshill. I’ll review this early next week on my way back.

**Comment by apreshill** [comment]
Sounds good, thanks!

**Comment by ismayc** [comment]
Tried to address this but couldn't figure out what the problem was. Moving it to later in the document with a name like `package-bakeoff` or using `infer.R` directly from the {infer} package still caused the same problem. Providing more forced hierarchy in `_pkgdown.yml` appears to solved it in #2.

**Comment by ismayc** [comment]
Netlify preview is at https://deploy-preview-2--bakeoff.netlify.com/reference/index.html.

**Comment by apreshill** [comment]
This is awesome, and I like the hierarchy better too. Thank you!!
