### ISSUE TITLE
Release bakeoff 0.2.0

### ISSUE THREAD

**Issue by rich-iannone** [apreshill/bakeoff#17]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] Review pkgdown reference index for, e.g., missing topics
* [ ] Draft blog post

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by apreshill** [comment]
Note:

> W  checking Rd cross-references ...
   Missing link or links in documentation object 'scale_bakeoff.Rd':
     ‘bakeoff_palettes’
   
   See section 'Cross-references' in the 'Writing R Extensions' manual.

**Comment by apreshill** [comment]
From RHub:

N  checking for detritus in the temp directory
   Found the following files/directories:
     'lastMiKTeXException'
